[package]
name = "functions-3"
version = "0.1.0"
authors = ["Brent Salisbury <brent.salisbury@docker.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
